### ISSUE TITLE
pin OSRM to most recent release

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/py-osrm#16]
I just realized we're using the latest master commit, but we should really stick with releases for OSRM. The graph structure easily breaks between releases, meaning any 2 commits on master can do the same.

**Comment by whytro** [comment]
To clarify, this was to pin OSRM to a specific commit hash rather than the actual release packages right? The CI for py-osrm was pinned [here](https://github.com/gis-ops/py-osrm/blob/b95c1318bbfebb089a27de10c19fd86ce4496f93/.github/workflows/osrm-backend.yml#L23), and I've just added an additional line to the osrm-python manylinux image that should do the same.

**Comment by nilsnolde** [comment]
The manylinux image can be pinned too, but that's not so important as I'd expect to always have the latest working version of the image online. I meant more pointing our OSRM dependency to an actual release, i.e. the commit of 5.27.1: https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.27.1. In fact, it's not that important either maybe.. If we stick to releases instead of tip of master, new releases of py-osrm will break graph structures likely as well. If that's happening because of new master commits or a new release, is actually irrelevant.
